### ISSUE TITLE
dev server and client dont work toghether

### ISSUE THREAD

**Issue by kordeviant** [eddyystop/feathers-starter-react-redux-login-roles#1]
on 1 process i run "npm start" and on the other i run "npm run build:devserver"
result is that localhost:8080 has green react connected but next line "cannot get /"

**Comment by eddyystop** [comment]
The version of the repo you tried was quickly pushed for someone to look at and try. That person reported he got it working but perhaps he made some changes without telling me.

My code has moved on since that version, especially in the area that maybe be causing the issue. The build process is now pretty complete. Please get the new version. I'm running node 6.2.2.

To use devserver:
`npm run build:devserver` on one process
`npm run start:devserver` on another
point browser at `localhost:3030`.

For production:
`npm run build`, then `npm start`.

Lemme  know.

**Comment by kordeviant** [comment]
thanks the "can not get / " error is gone .
